# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
